### ISSUE TITLE
Create topical source set

### ISSUE THREAD

**Issue by HeleenE** [opensanctions/storyweb#2]
1. create a GU subset 
- filter GU articles on pillar/news & content type article

2. further filter down GU subset
- somehow decide on a keyword, or topic, or label to further narrow down the set
- run spacy on news subset
- look at textcategorizer pipeline part results

**Comment by HeleenE** [comment]
1. create a GU subset 
- filter GU articles on pillar/news & content type article

2. further filter down GU subset
- ~somehow decide on a keyword, or topic, or label to further narrow down the set~ DM is analysing the GU data to create a distribution of keywords so we can make a topical selection based on keywords
- ~run spacy on news subset~
- ~look at textcategorizer pipeline part results~
Default models have no pre-trained textcat component, so this option is off the table.

**Comment by pudo** [comment]
Some guardian keywords I think would make a good starter set:

* law/human-rights 
* us-news/us-crime
* business/banking 
* technology/cryptocurrencies
* business/shipping-industry 
* law/criminal-justice
* business/financial-sector
* money/scamsandfraud 
* business/financial-conduct-authority 
* world/roman-abramovich 
* business/internationaltrade
* business/supply-chain-crisis
* money/tax

**Comment by HeleenE** [comment]
So you suggest making a subset with all of these? Or pick one?

**Comment by HeleenE** [comment]
https://docs.google.com/spreadsheets/d/1cQPozkD4bpbEcdCdDGfRMiMGfcBNU0dzjAeg4CSQATE/edit#gid=423272934
