### ISSUE TITLE
Define format for input articles

### ISSUE THREAD

**Issue by HeleenE** [opensanctions/storyweb#3]
Working on this here: https://github.com/pudo/articledata

**Comment by pudo** [comment]
This format is now actively used between `mediacrawl` and `storyweb` to exchange the extracted articles. 

https://github.com/opensanctions/storyweb/blob/main/storyweb/pipeline.py#L45

Closing as no-op, unless you want to keep it open for converting the Guardian archive into the `articledata` format?
